export const NOME_SISTEMA = 'Desbravadores'

export * from './enums'
export * from './permissoes'
export * from './datas'
export * from './formulas'
export * from './contratos/comum'
export * from './contratos/auth'
export * from './contratos/eu'
export * from './contratos/desbravadores'
export * from './contratos/unidades'
export * from './contratos/usuarios'
export * from './contratos/classes'
export * from './contratos/especialidades'
export * from './contratos/saude'
